In [1]:
import torch

In [2]:
i = torch.ones([3,1,8])
q = torch.ones(8, 8)
k = torch.ones(8, 8)
v = torch.ones(8, 8)
o = torch.ones(8, 8)

In [3]:
q[:, 0:4] = 0
k[:, 0:4] = 0
v[:, 0:4] = 0
o[0:4, :] = 0
q,k,v,o

(tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
       

In [4]:
q_mm = (i @ q).view(3,1,2,4).permute(0,2,1,3).view(6,1,4)
q_mm

tensor([[[0., 0., 0., 0.]],

        [[8., 8., 8., 8.]],

        [[0., 0., 0., 0.]],

        [[8., 8., 8., 8.]],

        [[0., 0., 0., 0.]],

        [[8., 8., 8., 8.]]])

In [5]:
k_mm = (i @ k).view(3,1,2,4).permute(0,2,1,3).view(6,1,4).permute(0,2,1)
k_mm

tensor([[[0.],
         [0.],
         [0.],
         [0.]],

        [[8.],
         [8.],
         [8.],
         [8.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[8.],
         [8.],
         [8.],
         [8.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[8.],
         [8.],
         [8.],
         [8.]]])

In [6]:
bmm1 = q_mm @ k_mm
bmm1

tensor([[[  0.]],

        [[256.]],

        [[  0.]],

        [[256.]],

        [[  0.]],

        [[256.]]])

In [7]:
vi = (i @ v).view(3,1,2,4).permute(0,2,1,3).view(6,1,4)
vi

tensor([[[0., 0., 0., 0.]],

        [[8., 8., 8., 8.]],

        [[0., 0., 0., 0.]],

        [[8., 8., 8., 8.]],

        [[0., 0., 0., 0.]],

        [[8., 8., 8., 8.]]])

In [8]:
bmm2 = bmm1 @ vi
bmm2

tensor([[[   0.,    0.,    0.,    0.]],

        [[2048., 2048., 2048., 2048.]],

        [[   0.,    0.,    0.,    0.]],

        [[2048., 2048., 2048., 2048.]],

        [[   0.,    0.,    0.,    0.]],

        [[2048., 2048., 2048., 2048.]]])

In [9]:
oi = bmm2.view(3,2,1,4).permute(0,2,1,3).view(3,1,8)
oi

tensor([[[   0.,    0.,    0.,    0., 2048., 2048., 2048., 2048.]],

        [[   0.,    0.,    0.,    0., 2048., 2048., 2048., 2048.]],

        [[   0.,    0.,    0.,    0., 2048., 2048., 2048., 2048.]]])

In [10]:
o

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
oi @ o

tensor([[[8192., 8192., 8192., 8192., 8192., 8192., 8192., 8192.]],

        [[8192., 8192., 8192., 8192., 8192., 8192., 8192., 8192.]],

        [[8192., 8192., 8192., 8192., 8192., 8192., 8192., 8192.]]])